from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RULES_FILE = ROOT / "rules" / "custom-direct.txt"
DIST_FILE = ROOT / "dist" / "whitelist-overlay.yaml"

PROVIDERS = [
    ("applications", "classical", "applications.txt"),
    ("private", "domain", "private.txt"),
    ("direct", "domain", "direct.txt"),
    ("lancidr", "ipcidr", "lancidr.txt"),
    ("cncidr", "ipcidr", "cncidr.txt"),
]


def load_custom_rules() -> list[str]:
    rules: list[str] = []
    for raw_line in RULES_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        rules.append(line)
    return rules


def render_rule_providers(base_url: str) -> str:
    lines = ["rule-providers:\n"]
    for name, behavior, filename in PROVIDERS:
        lines.extend(
            [
                f"  {name}:\n",
                "    type: http\n",
                f"    behavior: {behavior}\n",
                "    format: text\n",
                f"    path: ./ruleset/loyalsoldier/{filename}\n",
                "    interval: 86400\n",
                f"    url: {base_url.rstrip('/')}/{filename}\n",
            ]
        )
    return "".join(lines)


def render_proxy_groups() -> str:
    return """proxy-groups:
  - name: 代理模式
    type: select
    proxies:
      - 绕过大陆丨白名单(Whitelist)
      - 绕过大陆丨黑名单(GFWlist)

  - name: 节点选择
    type: select
    proxies:
      - PROXY
      - DIRECT

  - name: PROXY
    type: select
    proxies:
      - 节点选择
      - DIRECT

  - name: 绕过大陆丨黑名单(GFWlist)
    type: select
    proxies:
      - DIRECT

  - name: 绕过大陆丨白名单(Whitelist)
    type: select
    proxies:
      - PROXY
"""


def render_dns() -> str:
    return """dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  prefer-h3: false
  respect-rules: true
  use-system-hosts: false
  cache-algorithm: arc
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - +.msftconnecttest.com
    - +.msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - localhost.work.weixin.qq.com
  default-nameserver:
    - 223.5.5.5
    - 1.2.4.8
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://77.88.8.8/dns-query
    - https://8.8.4.4/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://208.67.222.222/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://9.9.9.9/dns-query
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  direct-nameserver-follow-policy: false
  nameserver-policy:
    geosite:cn:
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
"""


def render_rules(custom_rules: list[str]) -> str:
    lines = ["rules:\n"]
    for rule in custom_rules:
        lines.append(f"  - {rule}\n")
    lines.extend(
        [
            "  - RULE-SET,applications,DIRECT\n",
            "  - RULE-SET,private,DIRECT\n",
            "  - RULE-SET,direct,DIRECT\n",
            "  - RULE-SET,lancidr,DIRECT,no-resolve\n",
            "  - RULE-SET,cncidr,DIRECT,no-resolve\n",
            "  - GEOIP,LAN,DIRECT,no-resolve\n",
            "  - GEOIP,CN,DIRECT,no-resolve\n",
            "  - MATCH,代理模式\n",
        ]
    )
    return "".join(lines)


def build(base_url: str = "https://083105.xyz/rules/loyalsoldier") -> None:
    DIST_FILE.parent.mkdir(parents=True, exist_ok=True)
    custom_rules = load_custom_rules()
    output = [
        "# Generated by scripts/build_overlay.py\n",
        render_dns(),
        "\n",
        render_rule_providers(base_url),
        "\n",
        render_proxy_groups(),
        "\n",
        render_rules(custom_rules),
    ]
    DIST_FILE.write_text("".join(output), encoding="utf-8")
    print(f"wrote {DIST_FILE}")


if __name__ == "__main__":
    build()

